### PR TITLE
Outline fixes

### PR DESCRIPTION
**Pull request by yaroslavyaroslav**
Found it that initial outline release has missing protocol and enum vars to outline. Fixed.

### CODE REVIEW

**Comment by yaroslavyaroslav** [comment]
@maxdeviant sorry for spamming with that. Just a hot fix of an outline declaration (not sure why `toml` file showed as modified here)

**Comment by yaroslavyaroslav** [comment]
@maxdeviant could you please consider to merge this fix for swift lang?

**Comment by notpeter** [comment]
@yaroslavyaroslav Apologies for the delay.

1. Can you make sure you've signed the Zed CLA: https://zed.dev/cla (if you have, it'll have a date at the bottom).
2. Can you make sure your gmail address is added to your GitHub profile so that cla-bot can match your email to github

This change works great for me.
Screenshot 2024-11-20 at 13 21 34

3. I've removed the version number change from this commit.  In general, we try to put version bumps in separate commits.  We should add some docs explaining this, but it makes it easier to integrate/revert changesets independently without having conflicts/dependencies around version numbers.

**Comment by yaroslavyaroslav** [comment]
@notpeter yeah, I was missed mail that I use for git here, now I added it. So feel free to rerun the bot once again.

Thank you for your clarification about your changes to this PR allied, I'm totally fine with them.

**Comment by notpeter** [comment]
@cla-bot check

**Comment by notpeter** [comment]
Thanks! v0.3.2 should be available with this in a few minutes.

**Pull request merged**
